version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - redis

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
